### ISSUE TITLE
put 6.5 km MAR into the ldeo-glaciology bucket

### ISSUE THREAD

**Issue by jkingslake** [ldeo-glaciology/pangeo-MAR#4]
This will involve running gsutil from Helhiem server (based at lamont).

**Comment by raf-antwerpen** [comment]
To get the MAR netcdfs from the FTP to the local server use these steps:
1) log into server and move to desired directory
2) log into FTP with "ftp ftp.climato.be"
3) move to data directory and do "mget <FILES>". Accept each file with "y"

**Comment by raf-antwerpen** [comment]
To transfer MAR netcdfs from local server to Google Bucket use these steps:
1) move to data directory on server and do "gcloud auth login" to authorize write access to Google Bucket
2) do gsutil cp ./*.nc gs://ldeo-glaciology/MAR/6.5km/ to move all files in current directory to Google Bucket

**Comment by jkingslake** [comment]
@raf-antwerpen let's leave this open until we have all the data up there, then post a link to it and a code snippet showing how to load individual NCs. Then close it.

**Comment by raf-antwerpen** [comment]
All the data is already up on the bucket at: https://console.cloud.google.com/storage/browser/ldeo-glaciology/MAR/6.5km

**Comment by raf-antwerpen** [comment]
Just found out that the MAR output I just uploaded contains almost no variables besides lat and long. Looking for a better dataset right now

**Comment by raf-antwerpen** [comment]
Just uploaded complete MAR outputs to the bucket

**Comment by jkingslake** [comment]
Nice. Could you add a code snippet to load and plot a field from one of the
NCs?

**Comment by jkingslake** [comment]
Here you go. This loads one of them and plots it as an interactive figure with a slider for time. 

This works for me in leap.2i2c.cloud, with a cluster running. Let's talk about how to get a cluster running. 

It is contained in a new NB I added to the repo: https://github.com/ldeo-glaciology/pangeo-MAR/blob/main/loadMARnetcdfs_2.ipynb

```
import gcsfs
import xarray as xr
import hvplot.xarray
 
gcs = gcsfs.GCSFileSystem()

url = 'gs://ldeo-glaciology/MAR/6.5km/MARv3.12-6_5km-daily-ERA5-2000.nc'  
#url = 'gs://ldeo-glaciology/MAR/6.5km/MARv3.12-6_5km-daily-ERA5-2001.nc'  


of = gcs.open(url, mode='rb')
ds = xr.open_dataset(of,chunks=-1)    # need the chunks arguement to make it load as dask xarray
print(f"Total size of this year of data: {ds.nbytes/1e9} Gb")

## plotting
### use hvplot as its makes nice interactive plots
options = dict(x='x', y='y', clim=(0.2, 1), width=500, height=700, cmap='greys_r')

ds.AL2.hvplot(**options)
```
![image](https://user-images.githubusercontent.com/48723181/194650950-5a862211-4bc6-4cf2-bce3-dcdfa76044ee.png)

**Comment by jkingslake** [comment]
closing this as done
